

boe:
  DB:
    host: localhost
    password: boe
    port: 3306
    user: root
    database: boe


online:
  avatar: 'https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png'
  access: 0
  DB:
    host: localhost
    password: boe
    port: 3306
    user: root
    database: boe
