name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root

    - name: Run simple test
      run: |
        echo "Testing basic functionality..."
        poetry run python -c "import src.client.base_client; print('Base client imports successfully')"
        poetry run python -c "import src.utils.environment; print('Environment utils work')"
        echo "Basic imports successful!"

    - name: Run basic pytest
      run: |
        poetry run pytest --version
        echo "pytest is working"

  notify:
    needs: [test]
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Notify on success
      if: ${{ needs.test.result == 'success' }}
      run: |
        echo "✅ Basic CI checks passed!"

    - name: Notify on failure
      if: ${{ needs.test.result == 'failure' }}
      run: |
        echo "❌ CI checks failed!"
        exit 1
